### ISSUE TITLE
Epic - Convert into monorepo

### ISSUE THREAD

**Issue by briancldo** [briancldo/chess#116]
ideal monorepo workflow/setup:

- [x] https://github.com/briancldo/chess/issues/117
- web ui directory
- backend directory

<hr />

- [x] https://github.com/briancldo/chess/issues/118
- shares some tooling: eslint, prettier, tsconfig, commitlint, etc., and respective commands
  - can extend/override eslint, etc. with directory-specific config
- shares some code
<hr />

- [x] https://github.com/briancldo/chess/issues/119
- can be started locally together/apart
- can be deployed together/apart
